"""ORION Phase 1 - Normative Data Contracts.

This module defines the 9 normative data contracts specified in the ORION
Architecture v0.5 baseline. All contracts inherit from `BaseContract` which
enforces standard metadata, cryptographic integrity (SHA-256 hashing and HMAC
signing), serialization, and validation.

Normative Contracts:
1. Observation - Sensor data and observation state.
2. BeliefState - Filtered world state estimate with covariance.
3. Goal - High-level task or objective specification.
4. ActionProposal - Candidate action generated by Cognitive Plane.
5. ActionAuthorization - Time-bounded, constrained execution lease.
6. ActionExecutionResult - Outcome and telemetry from Control Plane.
7. SafetyDecision - Overrides, halts, and blocks from Safety Enforcement.
8. AuditEvent - Immutable audit trail record with hash chain integrity.
9. MemoryWrite - Cognitive memory storage request.
"""

import hashlib
import hmac
import json
import time
import uuid
from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Union

# -----------------------------------------------------------------------------
# Enums and Constants
# -----------------------------------------------------------------------------

class Plane(str, Enum):
    """ORION Architectural Planes."""
    STATE = "StatePlane"
    COGNITIVE = "CognitivePlane"
    ACTION_ARBITRATION = "ActionArbitration"
    CONTROL = "ControlPlane"
    SAFETY_ENFORCEMENT = "SafetyEnforcement"
    SAFETY_ASSURANCE = "SafetyAssurance"
    AUDIT = "AuditPlane"
    MEMORY = "MemoryPlane"
    SECURITY = "SecurityPlane"
    ALL = "AllPlanes"


class GoalType(str, Enum):
    """Types of cognitive goals."""
    REACH_STATE = "reach_state"
    MAINTAIN_STATE = "maintain_state"
    AVOID_STATE = "avoid_state"
    OPTIMIZE = "optimize"




class GoalSource(str, Enum):
    FOUNDER = 'founder'
    OPERATOR = 'operator'
    AUTONOMOUS = 'autonomous'
    SAFETY = 'safety'
    SCHEDULED = 'scheduled'

class GoalPriority(int, Enum):
    """Goal priority tiers."""
    LOW = 1
    MEDIUM = 2
    HIGH = 3
    CRITICAL = 4


class RiskTier(int, Enum):
    """Action risk tier classification.

    Used by both contracts and arbitration modules.
    TIER_1 = lowest risk, TIER_3 = highest risk requiring SA approval.
    String aliases maintained for backward compatibility.
    """
    TIER_1 = 1   # Minimal/Low risk
    TIER_2 = 2   # Moderate risk
    TIER_3 = 3   # High/Critical risk

    # String aliases for backward compatibility
    MINIMAL = TIER_1
    LOW = TIER_1
    MODERATE = TIER_2
    HIGH = TIER_3
    CRITICAL = TIER_3


class ExecutionOutcome(str, Enum):
    """Action execution outcome status."""
    COMPLETED = "completed"
    FAILED = "failed"
    PARTIAL = "partial"
    REJECTED = "rejected"
    UNKNOWN = "unknown"


class ExecutionStage(str, Enum):
    """Lifecycle stage of action execution."""
    ACCEPTED = "accepted"
    TRANSMITTED = "transmitted"
    ACKNOWLEDGED = "acknowledged"
    EXECUTING = "executing"
    COMPLETED = "completed"
    VERIFIED = "verified"


class DecisionType(str, Enum):
    """Safety decision types."""
    OVERRIDE = "override"
    HALT = "halt"
    BLOCK = "block"
    MANDATE_SAFE_STATE = "mandate_safe_state"
    REVOKE_LEASE = "revoke_lease"
    ALERT = "alert"


class AuthorityScope(str, Enum):
    """Safety authority scope."""
    EXECUTION_TIME = "execution_time"  # Safety Enforcement
    POLICY_LEVEL = "policy_level"      # Safety Assurance


class SeverityLevel(str, Enum):
    """Severity levels for decisions and audit events."""
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"
    EMERGENCY = "emergency"


class AuditEventType(str, Enum):
    """Categories of audit events."""
    DECISION = "decision"
    ACTION = "action"
    STATE_TRANSITION = "state_transition"
    CONFIG_CHANGE = "config_change"
    SECURITY = "security"
    SAFETY = "safety"
    ERROR = "error"


class MemoryType(str, Enum):
    """Cognitive memory classifications."""
    EPISODIC = "episodic"
    SEMANTIC = "semantic"
    WORKING = "working"
    LONG_TERM = "long_term"


# Helper functions
def generate_contract_id() -> str:
    """Generate a unique contract identifier (UUIDv4)."""
    return str(uuid.uuid4())


def current_timestamp_ns() -> int:
    """Get current monotonic timestamp in nanoseconds."""
    return time.monotonic_ns()


def current_wall_clock_ms() -> int:
    """Get current wall clock time in milliseconds UTC."""
    return int(time.time() * 1000)


# -----------------------------------------------------------------------------
# Base Contract
# -----------------------------------------------------------------------------

@dataclass
class BaseContract:
    """Base dataclass for all ORION normative data contracts.

    Provides standard metadata, hash computation, HMAC signing, verification,
    dictionary conversion, and validation interface.
    """
    schema_version: str = "1.0.0"
    contract_version: str = "1.0.0"
    contract_id: str = field(default_factory=generate_contract_id)
    timestamp: int = field(default_factory=current_timestamp_ns)
    producer: str = ""
    consumer: str = ""
    correlation_id: str = field(default_factory=generate_contract_id)
    sequence_number: int = 1
    units: Dict[str, str] = field(default_factory=dict)
    coordinate_frame: Optional[str] = None
    signature: str = ""
    hash: str = ""

    @property
    def envelope(self):
        """Return self as the envelope - all contract fields are on BaseContract directly.
        Allows code using contract.envelope.field to access metadata fields."""
        return self

    def _canonical_payload_dict(self) -> Dict[str, Any]:
        """Return canonical dictionary representation excluding signature and hash."""
        data = asdict(self)
        data.pop("signature", None)
        data.pop("hash", None)
        return data

    def compute_hash(self) -> str:
        """Compute SHA-256 hash of canonical contract payload."""
        payload_dict = self._canonical_payload_dict()
        canonical_json = json.dumps(payload_dict, sort_keys=True, default=str)
        self.hash = hashlib.sha256(canonical_json.encode("utf-8")).hexdigest()
        return self.hash

    def sign(self, secret_key: str) -> str:
        """Sign the contract hash using HMAC-SHA256."""
        if not self.hash:
            self.compute_hash()
        mac = hmac.new(
            secret_key.encode("utf-8"),
            self.hash.encode("utf-8"),
            hashlib.sha256
        )
        self.signature = mac.hexdigest()
        return self.signature

    def verify_signature(self, secret_key: str) -> bool:
        """Verify HMAC-SHA256 signature against current contract content."""
        computed_hash = hashlib.sha256(
            json.dumps(self._canonical_payload_dict(), sort_keys=True, default=str).encode("utf-8")
        ).hexdigest()

        expected_mac = hmac.new(
            secret_key.encode("utf-8"),
            computed_hash.encode("utf-8"),
            hashlib.sha256
        ).hexdigest()

        return hmac.compare_digest(self.signature, expected_mac)

    def validate(self) -> bool:
        """Validate metadata and contract invariant rules.

        Subclasses should override and call super().validate().
        Raises ValueError if invalid.
        """
        if not self.contract_version:
            raise ValueError("contract_version is mandatory")
        if not self.schema_version:
            raise ValueError("schema_version is mandatory")
        if not self.contract_id:
            raise ValueError("contract_id is mandatory")
        if not self.producer:
            raise ValueError("producer is mandatory")
        if not self.consumer:
            raise ValueError("consumer is mandatory")
        if not self.correlation_id:
            raise ValueError("correlation_id is mandatory")
        if self.sequence_number < 0:
            raise ValueError("sequence_number must be non-negative")
        if self.timestamp <= 0:
            raise ValueError("timestamp must be positive")
        return True

    def to_dict(self) -> Dict[str, Any]:
        """Export contract dataclass to dictionary."""
        if not self.hash:
            self.compute_hash()
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "BaseContract":
        """Instantiate contract from dictionary and run validation."""
        instance = cls(**data)
        instance.validate()
        return instance


# -----------------------------------------------------------------------------
# Contract 1: Observation
# -----------------------------------------------------------------------------

@dataclass
class Observation(BaseContract):
    """1. Observation Contract.

    Produced by State Plane, consumed by Cognitive Plane and Action Arbitration.
    Encapsulates raw and preprocessed sensor data with confidence and latency telemetry.
    """
    sensor_id: str = "sensor_0"
    sensor_type: str = "camera"
    raw_data: Union[bytes, str, Dict[str, Any]] = field(default_factory=dict)
    processed_data: Optional[Dict[str, Any]] = None
    confidence: float = 1.0
    timestamp_sensor: int = field(default_factory=current_timestamp_ns)
    latency: int = 0  # nanoseconds
    uncertainty: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        if not self.producer:
            self.producer = Plane.STATE.value
        if not self.consumer:
            self.consumer = Plane.COGNITIVE.value

    def validate(self) -> bool:
        super().validate()
        if not self.sensor_id:
            raise ValueError("Observation.sensor_id is mandatory")
        if not self.sensor_type:
            raise ValueError("Observation.sensor_type is mandatory")
        if not (0.0 <= self.confidence <= 1.0):
            raise ValueError(f"Observation.confidence ({self.confidence}) must be in [0.0, 1.0]")
        if self.timestamp_sensor <= 0:
            raise ValueError("Observation.timestamp_sensor must be positive")
        if self.latency < 0:
            raise ValueError("Observation.latency must be non-negative")
        return True


# -----------------------------------------------------------------------------
# Contract 2: BeliefState
# -----------------------------------------------------------------------------

@dataclass
class BeliefState(BaseContract):
    """2. BeliefState Contract.

    Produced by State Plane, consumed by Cognitive Plane, Action Arbitration, Safety Enforcement.
    Provides estimated world state, object tracking, spatial pose, and covariance matrices.
    """
    state_revision: int = 0
    position: List[float] = field(default_factory=lambda: [0.0, 0.0, 0.0])
    orientation: List[float] = field(default_factory=lambda: [0.0, 0.0, 0.0, 1.0])
    velocity: Optional[List[float]] = field(default_factory=lambda: [0.0, 0.0, 0.0])
    objects: List[Dict[str, Any]] = field(default_factory=list)
    uncertainty: Dict[str, Any] = field(default_factory=lambda: {
        "position_covariance": [[0.01, 0.0, 0.0], [0.0, 0.01, 0.0], [0.0, 0.0, 0.01]],
        "orientation_covariance": [[0.01, 0.0, 0.0], [0.0, 0.01, 0.0], [0.0, 0.0, 0.01]],
        "classification_confidence": 0.95
    })
    staleness: int = 0  # nanoseconds
    sensor_health: Dict[str, str] = field(default_factory=dict)
    confidence: float = 1.0

    def __post_init__(self):
        if not self.producer:
            self.producer = Plane.STATE.value
        if not self.consumer:
            self.consumer = Plane.COGNITIVE.value
        if self.coordinate_frame is None:
            self.coordinate_frame = "world"

    def validate(self) -> bool:
        super().validate()
        if self.state_revision < 0:
            raise ValueError("BeliefState.state_revision must be non-negative")
        if len(self.position) != 3:
            raise ValueError("BeliefState.position must be a 3D vector [x, y, z]")
        if len(self.orientation) != 4:
            raise ValueError("BeliefState.orientation must be a 4D quaternion [x, y, z, w]")
        if not (0.0 <= self.confidence <= 1.0):
            raise ValueError(f"BeliefState.confidence ({self.confidence}) must be in [0.0, 1.0]")
        if self.staleness < 0:
            raise ValueError("BeliefState.staleness must be non-negative")
        return True


# -----------------------------------------------------------------------------
# Contract 3: Goal
# -----------------------------------------------------------------------------

@dataclass
class Goal(BaseContract):
    """3. Goal Contract.

    Produced by Cognitive Plane, consumed by Action Arbitration.
    Defines high-level objective, priority, constraints, and deadline.
    """
    goal_id: str = field(default_factory=generate_contract_id)
    description: str = "Default cognitive target goal"
    goal_type: str = GoalType.REACH_STATE.value
    goal_parameters: Dict[str, Any] = field(default_factory=dict)
    constraints: Dict[str, Any] = field(default_factory=dict)
    priority: int = GoalPriority.MEDIUM.value
    deadline: Optional[int] = None  # monotonic_ns
    source: str = "autonomous"
    justification: str = "Autonomous goal generation by Cognitive Plane"
    target_state: Optional[Dict[str, Any]] = None

    def __post_init__(self):
        if not self.producer:
            self.producer = Plane.COGNITIVE.value
        if not self.consumer:
            self.consumer = Plane.ACTION_ARBITRATION.value

    def validate(self) -> bool:
        super().validate()
        if not self.goal_id:
            raise ValueError("Goal.goal_id is mandatory")
        if not self.description:
            raise ValueError("Goal.description is mandatory")
        if self.priority not in [e.value for e in GoalPriority]:
            raise ValueError(f"Goal.priority ({self.priority}) must be 1 (low), 2 (medium), 3 (high), or 4 (critical)")
        if self.goal_type not in [e.value for e in GoalType]:
            raise ValueError(f"Goal.goal_type ({self.goal_type}) is invalid")
        if not self.justification:
            raise ValueError("Goal.justification is mandatory")
        return True


# -----------------------------------------------------------------------------
# Contract 4: ActionProposal
# -----------------------------------------------------------------------------

@dataclass
class ActionProposal(BaseContract):
    """4. ActionProposal Contract.

    Produced by Cognitive Plane, consumed by Action Arbitration.
    Represents candidate action with target actuator/device, parameters, expected outcome, and risk assessment.
    """
    action_id: str = field(default_factory=generate_contract_id)
    goal_id: Optional[str] = None
    action_type: str = "navigate"
    target_entity: str = "robot_base"
    action_parameters: Dict[str, Any] = field(default_factory=dict)
    estimated_duration_ms: int = 1000
    expected_outcome: Dict[str, Any] = field(default_factory=dict)
    risk_tier: RiskTier = RiskTier.TIER_1
    risk_assessment: Dict[str, Any] = field(default_factory=lambda: {
        "risk_tier": 1,
        "hazards": ["minor_collision_risk"],
        "mitigations": ["speed_limit_enforced", "cbf_barrier_active"]
    })
    requested_channel: str = "REALTIME"
    state_revision: int = 1
    policy_version: str = "1.0.0"
    preconditions: Dict[str, Any] = field(default_factory=dict)
    expected_postconditions: Dict[str, Any] = field(default_factory=dict)
    cognitive_confidence: float = 0.9

    # Backward-compatible aliases
    @property
    def target(self):
        return self.target_entity

    @target.setter
    def target(self, value):
        self.target_entity = value

    @property
    def parameters(self):
        return self.action_parameters

    @parameters.setter
    def parameters(self, value):
        self.action_parameters = value

    @property
    def expected_duration(self):
        return self.estimated_duration_ms

    @expected_duration.setter
    def expected_duration(self, value):
        self.estimated_duration_ms = value

    def __post_init__(self):
        if not self.producer:
            self.producer = Plane.COGNITIVE.value
        if not self.consumer:
            self.consumer = Plane.ACTION_ARBITRATION.value

    def validate(self) -> bool:
        super().validate()
        if not self.action_id:
            raise ValueError("ActionProposal.action_id is mandatory")
        if not self.action_type:
            raise ValueError("ActionProposal.action_type is mandatory")
        if not self.target:
            raise ValueError("ActionProposal.target is mandatory")
        if not (0.0 <= self.cognitive_confidence <= 1.0):
            raise ValueError(f"ActionProposal.cognitive_confidence ({self.cognitive_confidence}) must be in [0.0, 1.0]")
        if "risk_tier" not in self.risk_assessment:
            raise ValueError("ActionProposal.risk_assessment must contain 'risk_tier'")
        if "hazards" not in self.risk_assessment:
            raise ValueError("ActionProposal.risk_assessment must contain 'hazards'")
        if "mitigations" not in self.risk_assessment:
            raise ValueError("ActionProposal.risk_assessment must contain 'mitigations'")
        return True


# -----------------------------------------------------------------------------
# Contract 5: ActionAuthorization (Lease)
# -----------------------------------------------------------------------------

@dataclass
class ActionAuthorization(BaseContract):
    """5. ActionAuthorization Contract (Lease).

    Produced by Action Arbitration, consumed by Control Plane and Safety Enforcement.
    Grants a cryptographic, bounded lease binding the action to belief state revision and policy version.
    """
    lease_id: str = field(default_factory=generate_contract_id)
    action_id: str = field(default_factory=generate_contract_id)
    authorized_by: str = Plane.ACTION_ARBITRATION.value
    target_entity: str = "robot_base"
    state_revision_binding: int = 0
    policy_version_binding: str = "1.0.0"
    risk_tier: str = RiskTier.LOW.value
    safety_constraints: Dict[str, Any] = field(default_factory=lambda: {
        "cbf_boundaries": {},
        "rate_limits": {"max_velocity": 1.5, "max_acceleration": 2.0},
        "spatial_bounds": {"x_min": -10.0, "x_max": 10.0, "y_min": -10.0, "y_max": 10.0},
        "force_limits": {"max_force": 50.0}
    })
    expiry: int = field(default_factory=lambda: current_timestamp_ns() + 5_000_000_000)  # +5s
    execution_count_limit: int = 1
    executions_consumed: int = 0
    permitted_channel: str = "realtime"
    safety_assurance_approval: Optional[str] = None
    authorization_signature: Optional[str] = None
    nonce: str = field(default_factory=lambda: uuid.uuid4().hex)

    def __post_init__(self):
        if not self.producer:
            self.producer = Plane.ACTION_ARBITRATION.value
        if not self.consumer:
            self.consumer = Plane.CONTROL.value

    def validate(self) -> bool:
        super().validate()
        if not self.lease_id:
            raise ValueError("ActionAuthorization.lease_id is mandatory")
        if not self.action_id:
            raise ValueError("ActionAuthorization.action_id is mandatory")
        if not self.authorized_by:
            raise ValueError("ActionAuthorization.authorized_by is mandatory")
        if not self.policy_version_binding:
            raise ValueError("ActionAuthorization.policy_version_binding is mandatory")
        if self.execution_count_limit < 1:
            raise ValueError("ActionAuthorization.execution_count_limit must be >= 1")
        if self.executions_consumed < 0 or self.executions_consumed > self.execution_count_limit:
            raise ValueError(f"ActionAuthorization.executions_consumed ({self.executions_consumed}) invalid for limit {self.execution_count_limit}")
        if self.expiry <= 0:
            raise ValueError("ActionAuthorization.expiry must be positive")
        return True


# -----------------------------------------------------------------------------
# Contract 6: ActionExecutionResult
# -----------------------------------------------------------------------------

@dataclass
class ActionExecutionResult(BaseContract):
    """6. ActionExecutionResult Contract.

    Produced by Control Plane, consumed by Cognitive Plane, Action Arbitration, and Audit Plane.
    Reports detailed telemetry, actual duration, final state, and independent verifications.
    """
    action_id: str = field(default_factory=generate_contract_id)
    lease_id: str = field(default_factory=generate_contract_id)
    outcome: str = ExecutionOutcome.COMPLETED.value
    execution_stage: str = ExecutionStage.COMPLETED.value
    actual_duration: int = 0  # ms
    actual_effects: Dict[str, Any] = field(default_factory=dict)
    verified_by: Optional[str] = None
    deviation: Optional[Dict[str, Any]] = None
    deviation_reason: Optional[str] = None
    sensor_verification: Optional[Dict[str, Any]] = None
    safety_events: List[Dict[str, Any]] = field(default_factory=list)

    @property
    def result(self):
        """Read-only alias for outcome field (used by simulation and tests)."""
        return self.outcome

    @property
    def final_state(self):
        """Read-only alias for actual_effects field (used by state plane)."""
        return self.actual_effects

    def __post_init__(self):
        if not self.producer:
            self.producer = Plane.CONTROL.value
        if not self.consumer:
            self.consumer = Plane.COGNITIVE.value

    def validate(self) -> bool:
        super().validate()
        if not self.action_id:
            raise ValueError("ActionExecutionResult.action_id is mandatory")
        if not self.lease_id:
            raise ValueError("ActionExecutionResult.lease_id is mandatory")
        if self.outcome not in [e.value for e in ExecutionOutcome]:
            raise ValueError(f"ActionExecutionResult.outcome ({self.outcome}) is invalid")
        if self.execution_stage not in [e.value for e in ExecutionStage]:
            raise ValueError(f"ActionExecutionResult.execution_stage ({self.execution_stage}) is invalid")
        if self.actual_duration < 0:
            raise ValueError("ActionExecutionResult.actual_duration must be non-negative")
        return True


# -----------------------------------------------------------------------------
# Contract 7: SafetyDecision
# -----------------------------------------------------------------------------

@dataclass
class SafetyDecision(BaseContract):
    """7. SafetyDecision Contract.

    Produced by Safety Enforcement (execution time) or Safety Assurance (policy level).
    Broadcast to All Planes to command halts, overrides, lease revocations, or safe-state mandates.
    """
    decision_id: str = field(default_factory=generate_contract_id)
    decision_type: str = DecisionType.HALT.value
    authority_scope: str = AuthorityScope.EXECUTION_TIME.value
    scope: str = "global"  # global, plane_specific, action_specific, device_specific
    override_target: Optional[str] = None
    override_reason: str = "Safety constraint violation or manual E-stop trigger"
    reason_code: str = "E_STOP_ACTIVATED"
    severity: str = SeverityLevel.CRITICAL.value
    constraints: Dict[str, Any] = field(default_factory=dict)
    actions_required: List[str] = field(default_factory=lambda: ["halt_actuators", "enter_safe_state"])
    lease_id: Optional[str] = None
    state_transition: Optional[str] = "EMERGENCY"

    def __post_init__(self):
        if not self.producer:
            self.producer = Plane.SAFETY_ENFORCEMENT.value
        if not self.consumer:
            self.consumer = Plane.ALL.value

    def validate(self) -> bool:
        super().validate()
        if not self.decision_id:
            raise ValueError("SafetyDecision.decision_id is mandatory")
        if self.decision_type not in [e.value for e in DecisionType]:
            raise ValueError(f"SafetyDecision.decision_type ({self.decision_type}) is invalid")
        if self.authority_scope not in [e.value for e in AuthorityScope]:
            raise ValueError(f"SafetyDecision.authority_scope ({self.authority_scope}) is invalid")
        if self.severity not in [e.value for e in SeverityLevel]:
            raise ValueError(f"SafetyDecision.severity ({self.severity}) is invalid")
        if not self.override_reason:
            raise ValueError("SafetyDecision.override_reason is mandatory")
        return True


# -----------------------------------------------------------------------------
# Contract 8: AuditEvent
# -----------------------------------------------------------------------------

@dataclass
class AuditEvent(BaseContract):
    """8. AuditEvent Contract.

    Produced by any plane, consumed by Audit Plane.
    Uses wall-clock UTC timestamps and hash chaining for tamper-evident audit trailing.
    """
    event_id: str = field(default_factory=generate_contract_id)
    event_type: str = AuditEventType.ACTION.value
    event_data: Dict[str, Any] = field(default_factory=dict)
    actor: str = Plane.COGNITIVE.value
    decision_id: Optional[str] = None
    lease_id: Optional[str] = None
    severity: str = SeverityLevel.INFO.value
    previous_hash: str = "0000000000000000000000000000000000000000000000000000000000000000"
    storage_status: str = "stored"

    def __post_init__(self):
        if not self.producer:
            self.producer = Plane.COGNITIVE.value
        if not self.consumer:
            self.consumer = Plane.AUDIT.value
        if self.timestamp == 0:
            self.timestamp = current_wall_clock_ms()

    def validate(self) -> bool:
        super().validate()
        if not self.event_id:
            raise ValueError("AuditEvent.event_id is mandatory")
        if self.event_type not in [e.value for e in AuditEventType]:
            raise ValueError(f"AuditEvent.event_type ({self.event_type}) is invalid")
        if not self.actor:
            raise ValueError("AuditEvent.actor is mandatory")
        if not self.previous_hash:
            raise ValueError("AuditEvent.previous_hash is mandatory for hash chain integrity")
        return True


# -----------------------------------------------------------------------------
# Contract 9: MemoryWrite
# -----------------------------------------------------------------------------

@dataclass
class MemoryWrite(BaseContract):
    """9. MemoryWrite Contract.

    Produced EXCLUSIVELY by Cognitive Plane, consumed by Memory Plane.
    Requests durable or working memory storage with full cognitive provenance and permissions.
    """
    writer_id: str = "cognitive_agent_v1"
    writer_permissions: List[str] = field(default_factory=lambda: ["read", "write_working", "write_episodic"])
    memory_type: str = MemoryType.WORKING.value
    content: Dict[str, Any] = field(default_factory=dict)
    source_type: str = "cognitive_reasoning"
    provenance: Dict[str, Any] = field(default_factory=lambda: {
        "source": "gpt-4o",
        "source_confidence": 0.95,
        "correlation_id": generate_contract_id(),
        "timestamp_origin": current_timestamp_ns()
    })
    retention_policy: Dict[str, Any] = field(default_factory=lambda: {
        "ttl": 3600,
        "max_retrievals": 100
    })
    schema_version_memory: str = "1.0.0"
    contradiction_check: bool = True

    def __post_init__(self):
        if not self.producer:
            self.producer = Plane.COGNITIVE.value
        if not self.consumer:
            self.consumer = Plane.MEMORY.value

    def validate(self) -> bool:
        super().validate()
        # Architecture v0.5 B.9 Rule: Writer restriction
        if self.producer != Plane.COGNITIVE.value:
            raise ValueError(f"MemoryWrite producer MUST be '{Plane.COGNITIVE.value}', got '{self.producer}'")
        if not self.writer_id:
            raise ValueError("MemoryWrite.writer_id is mandatory")
        if self.memory_type not in [e.value for e in MemoryType]:
            raise ValueError(f"MemoryWrite.memory_type ({self.memory_type}) is invalid")
        if "source" not in self.provenance:
            raise ValueError("MemoryWrite.provenance must contain 'source'")
        if "source_confidence" not in self.provenance:
            raise ValueError("MemoryWrite.provenance must contain 'source_confidence'")
        conf = self.provenance.get("source_confidence", 0.0)
        if not (0.0 <= conf <= 1.0):
            raise ValueError(f"MemoryWrite.provenance.source_confidence ({conf}) must be in [0.0, 1.0]")
        return True
